Project/news aggregator/sample/sample/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views

urlpatterns = {
    path('admin/', admin.site.urls),
    path('hello/', views.show8),
    path('/home', views.show3),
    path('login/', views.show2),
    path('', views.topnews),
    path('contactus/', views.show4),
    path('blog/', views.show5),
    path('aboutus/', views.show6),
    path('signup/', views.show7),
    path('dashboardM/', views.show9),
    path('userdet/', views.adduser),
    path('insuser/', views.insuser),
    path('showusers/', views.showuser),
    path('edit/<int:id>', views.edit),
    path('update1/<int:id>', views.update1),
    path('delete/<int:id>', views.delete1),
    path('login2/', views.login2),
    path('logout/', views.logout),
    path('empform/', views.addempform),
    path('feedback', views.feedback),
    path('sports/', views.sports),
    path('worldnews/', views.worldnews),
    path('vadodaranews/', views.vadodaranews),
    path('ins_feedback/', views.ins_feedback),
    path('covid19/', views.covid19),
}

Project/news aggregator/sample/app1/models.py
from django.db import models
# Create your models here.
class userdet(models.Model):
    id=models.IntegerField(primary_key=True)
    name=models.CharField(max_length=30)
    psw=models.CharField(max_length=20)

class admindet(models.Model):
    id=models.IntegerField(primary_key=True)
    name=models.CharField(max_length=30)
    psw=models.CharField(max_length=20)

"""
class employee(models.Model):
    emid = models.IntegerField(primary_key=True)
    desig = models.CharField(max_length=30)
    file = models.FileField()
"""

class feedback(models.Model):
    fid = models.IntegerField(primary_key=True, auto_created=True)
    fname=models.CharField(max_length=100)
    emailid = models.CharField(max_length=70)
    contactno=models.CharField(max_length=20)
    feedback = models.TextField()
    status=models.BooleanField()


Project/news aggregator/sample/templates/aboutus.html
<!DOCTYPE html>
<html>
<head>
<title>Aboutus</title>
{% load static %}


 <link href="{% static 'css/s5.css' %}" rel="stylesheet" type="text/css" />
 <link href="{% static 'css/1.css' %}" rel="stylesheet" type="text/css" />

<style>
</style>
</head>

<body>
<div class="top">
    <a href="/aboutus">
        <div class="logo">
            <h2>DSPH News</h2>
        </div>
    </a>
    <div style="margin-left:45%" >
        <div class="menu">
            <center>
                <a href="/">Home</a>
                <a href="/aboutus">About</a>
                <a href="/contactus">Contact</a>
                <a href="/login">login</a>
                <a href="https://accounts.google.com/AccountChooser">signup</a>
            </center>
        </div>
    </div>
</div>
<div class="line"></div>
<div class="main">
 <div id="posts">
  <h2 id = "aboutus">About us</h2>
  <p id="aut">
  Our company was founded in California, but our mission is to facilitate access to information for the entire world, and in every language. To that end, we have offices in more than 60 countries, maintain more than 180 Internet domains and serve more than half of our results to people living outside the United States.
	</div>
 </div>

<div class="footer">
 <div class="logo">
  <h1>DSPH NEWS</h1>
 </div>
 <div class="desc">
  <p>Email : dsphnews@gmail.com</p>
  <p>Mobile : +91 8154850006</p>
  <p>Location :19/50 Mansarovar Complex,Opp Gurudwara,Chhani,Vadodara-391740</p>
 </div>
</div>
</body>
</html>

Project/news aggregator/sample/templates/addemp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}
</form>
</body>
</html>

Project/news aggregator/sample/templates/contactus.html
<!DOCTYPE html>
<html>
<head>
<title>contact us</title>
{% load static %}


 <link href="{% static 'css/s5.css' %}" rel="stylesheet" type="text/css" />
 <link href="{% static 'css/1.css' %}" rel="stylesheet" type="text/css" />

<style>
</style>
</head>

<body>
<div class="top">
    <a href="/aboutus">
        <div class="logo">
            <h2>DSPH News</h2>
        </div>
    </a>
    <div style="margin-left:45%" >
        <div class="menu">
            <center>
                <a href="/">Home</a>
                <a href="/aboutus">About</a>
                <a href="/contactus">Contact</a>
                <a href="/login">login</a>
                <a href="https://accounts.google.com/AccountChooser">signup</a>
            </center>
        </div>
    </div>
</div>
<div class="line"></div>
<div class="main">
 <div id="posts">
  <h2 id = "aboutus">About us</h2>
  <p>Email : dsphnews@gmail.com</p>
  <p>Mobile : +91 8154850006</p>
  <p>Location :19/50 Mansarovar Complex,Opp Gurudwara,Chhani,Vadodara-391740</p>
  </div>
 </div>
</body>
</html>

Project/news aggregator/sample/templates/dashboardM.html
<!DOCTYPE html>
<html>
<head>
<title>DSPH News</title>
{% load static %}


 <link href="{% static 'css/s5.css' %}" rel="stylesheet" type="text/css" />
 <link href="{% static 'css/1.css' %}" rel="stylesheet" type="text/css" />

<style>
</style>
</head>

<body>
{% if request.session.email %}
{% block content %}
<div class="navbar">
    <div class="top">
        <a href="/aboutus"></a>
        <div class="logo">
            <h2>DSPH News</h2>
        </div>
        <div class="seesion">
            <h2>  {{ request.session.email }} <a href="/logout/"> <img src="{% static 'img/logout.png' %}" height="40px" width="50px;"> </a></h2>
        </div>
    </div>
</div>
<div class="line"></div>
<div class="main">
    <div class="news">
        <h2>Recent News</h2>
            {% for i,j in data.items %}
                <div class="content">
                    <marquee direction="up" scrollamount=1>
                        <h3><p><a href="{{ i }} " class="a-content" onclick="return false;" >{{ j }}</a></p></h3>
                    </marquee>
                </div>
            {% endfor %}
    </div>

    <div class="news1">
        <h2>vadodara News</h2>
            {% for i,j in data1.items %}
                 <div class="content1">
                     <marquee direction="up" scrollamount=1>
                         <h3><p><a href="{{ i }} " class="a-content" onclick="return true;">{{ j }}</a></p></h3>
                     </marquee>
                 </div>
            {% endfor %}
    </div>

    <div class="art">
        <h2>Recent Articles</h2>

        <div class="art-content">
            <a href="https://accounts.google.com/AccountChooser" target="_self" id="s1">
                <div class="slideshow-container">
                        {% for i in data3 %}
                            <div class="mySlides fade">
                                <a href="{{ i.0.0 }}"><img src="{{ i.0.1 }} "  onclick="return false;" height="50%" width="100%">
                                <br><br><Br><br><br><Br><br><br>

                                    <div class="text"  onclick="return false;"><h3>{{ i.1 }}</h3></div>
                                </a>

                            </div>
                        {% endfor %}
                    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                    <a class="next" onclick="plusSlides(1)">&#10095;</a>
                </div><br>
                <div style="text-align:center">
                    <span class="dot" onclick="currentSlide(1)"></span>
                    <span class="dot" onclick="currentSlide(2)"></span>
                    <span class="dot" onclick="currentSlide(3)"></span>
                    <span class="dot" onclick="currentSlide(4)"></span>
                    <span class="dot" onclick="currentSlide(5)"></span>

                </div>
            </a>
            <!--p><h2><b>Click on picture to read Article</b></h2>
            </p-->
        </div>

    </div>
</div>



<div class="footer">
    <a href="/aboutus">

        <div class="logo">
            <h2>DSPH News</h2>
        </div>
    </a>
    <div class="desc">
        <p>Email :dsphnews@gmail.com<br>Mobile : +91 8154850006<br>                    Location :19/50 Mansarovar Complex,<br>Opp Gurudwara,Chhani,Vadodara-391740</p>
    </div>
</div>

<script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
}
</script>
{% endblock %}
{% else %}
{% include "home.html" %}
{% endif %}
</body>
</html>

Project/news aggregator/sample/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit</title>
</head>
<body>
<form method="post" action="/update1/{{user.id}}">
    {% csrf_token %}

    <h3> Update USer Detail</h3>
    Id: <input type="text" value="{{ user.id }}" name="id" id="id_id" disabled><br>
    Name: <input type="text" value="{{ user.name }}" name="name" id="id_name"><br>
    Password: <input type="text" value="{{ user.psw }}" name="psw" id="id_psw"><br>

    <button type="submit">Update</button>

</form>
</body>
</html>

Project/news aggregator/sample/templates/feedback.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>RATE US..!!</title>
    {% load static %}
    <link href="{% static 'css/feedback.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
<center>

        <div class="screen">
            <div class="screen-header">
                <div class="screen-header-left">
                    <div class="screen-header-button close"></div>
                    <div class="screen-header-button maximize"></div>
                    <div class="screen-header-button minimize"></div>
                </div>
            </div>
            <div class="screen-body">
                <div class="screen-body-item left">
                    <div class="app-title">
                        <h1>DSPH NEWS</h1>
                    </div>
                    <div class="app-contact"><h1>CONTACT INFO : +91 8154850006</h1></div>
                </div>
                <form name="feedbackform" action="/ins_feedback/" method="post">
                    {% csrf_token %}
                    <div class="screen-body-item">
                        <div class="app-form">
                            <div class="app-form-group">
                                <h3>
                                    <input class="app-form-control" placeholder="NAME" value="DSPH NEWS" name="fname">
                            </div>
                            <div class="app-form-group">
                                <input type="email" class="app-form-control" placeholder="EMAIL" name="emailid">
                            </div>
                            <div class="app-form-group">
                                <input type="number" class="app-form-control" placeholder="CONTACT NO" name="contactno">
                            </div>
                            <div class="app-form-group message">
                                <input class="app-form-control" placeholder="MESSAGE" name="feedback">
                                </h3>
                            </div>
                            <div class="app-form-group buttons">
                                <button class="app-form-button">CANCEL</button>
                                <button class="app-form-button" type="submit">SEND</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

</center>
</body>
</html>

Project/news aggregator/sample/templates/home.html
<!DOCTYPE html>
<html>
<head>
<title>DSPH News</title>
{% load static %}
    <link href="{% static 'css/bootstrap1.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/bootstrap2.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'js/js1.js'%}"></script>
    <script src="{% static 'js/js2.js'%}"></script>
    <script src="{% static 'js/js3.js'%}"></script>
    <script src="{% static 'js/js4.js'%}"></script>
    <link href="{% static 'css/s5.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/1.css' %}" rel="stylesheet" type="text/css">
   <style>
    .carousel-inner img {
    width: 100%;
    height: 100%;
    }
</style>
</head>
<body class="bg-dark">
<nav class="navbar navbar-expand-sm bg-success navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-light" href="/aboutus" style="color:white; font-weight:bold;">
                DSPH NEWS
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light"  href="/" >હોમ</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light"  href="/aboutus">અમારા વિશે</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light" href="/signup">એકાઉન્ટ બનાવો</a>
        </li>
    </ul>
     <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            મેનુ
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="/">GUJARAT NEWS</a>
            <a class="dropdown-item" href="/vadodaranews">VADODARA NEWS</a>
            <a class="dropdown-item" href="/sports">SPORTS</a>
            <a class="dropdown-item" href="/worldnews">WORLD NEWS</a>
           
        </div>
    </div>
    <ul  class="navbar-nav"   style="margin-left:60%;">
      <li class="nav-item">
        
    </li>
  </ul>




    <!--div class="top">
    <a href="/aboutus">
        <div class="logo">
            <h2>DSPH News</h2>
        </div>
    </a>
    <div style="margin-left:45%" >
        <div class="menu">
            <center>
                <a href="/">Home</a>
                <a href="/aboutus">About</a>
                <a href="/contactus">Contact</a>
                <a href="/login">login</a>
                <a href="https://accounts.google.com/AccountChooser">signup</a>
            </center>
        </div>
    </div>
</div-->
</nav>
<br>
<div class="continer-fluid">
    <div class="row">
    <!-- left side news -->
        <div class="col" >
            <h2 class="text-light center"><center>ગુજરાત(દિવ્ય ભાસ્કર)</center></h2>
                {% for i,j in data.items %}
                    <div class="content">
                        <marquee direction="up" scrollamount=1>
                            <h5><p><a href="{{ i }} " class="text-light" onclick="return false;" >{{ j }}</a></p></h5>
                        </marquee>
                    </div>
                {% endfor %}
        </div>

        <!-- The slideshow  -->

        <div class="col">
            <!-- Indicators -->
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
                </ol>

                <div class="carousel-inner">
                    {% for i in data3 %}
                        {% if forloop.counter == 1 %}
                            <div class="active carousel-item">
                                <a href="{{ i.0.0 }}"><img src="{{ i.0.1 }}" alt="First Slide" height=100% width="100%"></a>
                                <br><br><br><br><br><br>
                                <div class="carousel-caption">
                                        <h6>{{ i.1 }}</h6>
                                 </div>
                            </div>
                        {% else %}
                            <div class="carousel-item">
                                <a href="{{ i.0.0 }}"><img src="{{ i.0.1 }}" alt="First slide" height=100% width="100%"></a>
                                <br><br><br><br><br><br>
                                <div class="carousel-caption">
                                        <h6>{{ i.1 }}</h6>
                                </div>
                            </div>
                        {% endif %}


                    {% endfor %}
                </div>

                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>

                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>


            </div>

    </div>
     <div class="col" >
        <center><h2 class="text-light">ગુજરાત(TV9 ગુજરાતી)</h2></center>
            {% for i,j in data1.items %}
                <div class="content">
                    <marquee direction="up" scrollamount=1>
                        <h5><p><a href="{{ i }} " class="text-light" onclick="return false;" >{{ j }}</a></p></h5>
                    </marquee>
                </div>
            {% endfor %}
    </div>



</div>
    <div class="row">

        <div class="col-sm-4" >
            <span class="badge badge-warning" style="margin-left:5%">
            <a href="/aboutus">

                <h2 class="text-dark">DSPH News</h2>

            </a>
            </span>
        </div>
        <div class="col-sm-4">
            &nbsp;&nbsp;&nbsp;&nbsp;
        </div>
        <div class="col-sm-4" >
            <span class="badge badge-warning" style="margin-left:5%">
                <h5>Email :dsphnews@gmail.com<br>Mobile : +91 8154850006<br>Location :19/50 Mansarovar Complex,<br>Opp Gurudwara,Chhani,<br>Vadodara-391740</h5>
            </span>
        </div>

    </div>
</div>




<!--div class="main">
    <div class="news">
        <h2>Top News Gujarat(Divya Bhaskar)</h2>
            {% for i,j in data.items %}
                <div class="content">
                    <marquee direction="up" scrollamount=1>
                        <h3><p><a href="{{ i }} " class="a-content" onclick="return false;" >{{ j }}</a></p></h3>
                    </marquee>
                </div>
            {% endfor %}
    </div>

    <div class="news1">
        <h2>Top News Gujarat(tv9-gujarati)</h2>
            {% for i,j in data1.items %}
                 <div class="content1">
                     <marquee direction="up" scrollamount=1>
                         <h3><p><a href="{{ i }} " class="a-content" onclick="return true;">{{ j }}</a></p></h3>
                     </marquee>
                 </div>
            {% endfor %}
    </div>

    <div class="art">
        <h2>Recent Articles</h2>

        <div class="art-content">
            <a href="https://accounts.google.com/AccountChooser" target="_self" id="s1">
                <div class="slideshow-container">
                        {% for i in data3 %}
                            <div class="mySlides fade">
                                <a href="{{ i.0.0 }}"><img src="{{ i.0.1 }} "  onclick="return false;" height="50%" width="100%">
                                <br><br><Br><br><br><Br><br><br>

                                    <div class="text"  onclick="return false;"><h3>{{ i.1 }}</h3></div>
                                </a>

                            </div>
                        {% endfor %}
                    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                    <a class="next" onclick="plusSlides(1)">&#10095;</a>
                </div><br>
                <div style="text-align:center">
                    <span class="dot" onclick="currentSlide(1)"></span>
                    <span class="dot" onclick="currentSlide(2)"></span>
                    <span class="dot" onclick="currentSlide(3)"></span>
                    <span class="dot" onclick="currentSlide(4)"></span>
                    <span class="dot" onclick="currentSlide(5)"></span>

                </div>
            </a>
            <p><h2><b>Click on picture to read Article</b></h2>
            </p>
        </div>

    </div>
</div>

-->

<!--div class="footer">
    <a href="/aboutus">

        <div class="logo">
            <h2>DSPH News</h2>
        </div>
    </a>
    <div class="desc">
        <p>Email :dsphnews@gmail.com<br>Mobile : +91 8154850006<br>Location :19/50 Mansarovar Complex,Opp Gurudwara,Chhani,Vadodara-391740</p>
    </div>
</div-->

<script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
}
</script>
</body>
</html>

Project/news aggregator/sample/templates/login.html
<html>
<head>
	{% load static %}
	<link href="{% static 'css/3.css' %}" rel="stylesheet" type="text/css" />
<style>
body{
     background-image: url('de.jpg');
     background-color: #cccccc;
}
</style>
	<title> DSPH loginpage</title>
</head>

<form name="login-form" action="/login2/" method="post">
	{% csrf_token %}
<div class="main center " >
	<div class="box center " >
		<div class="icon center " >

		</div>
	  <h1>LOGIN</h1>
	  <div>
		    <p> EMAIL:-</P>
		    <input type="text" name="email" id="1" placeholder=""/>
	  </div>
	    <div>
		     <p> PASSWORD:-)</P>
		     <input type="password" name="password" id="2" placeholder=""/>
	    </div>
	         <button type=submit class="btn">login</button><br/>
		{% if messages %}
				{% for message in messages %}
					<li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
				{% endfor %}
			{% endif %}
	   </div>
	<div>

		</div>
	</div>
</form>
	</html>

Project/news aggregator/sample/templates/login1.html
 <a href="/signup" target="_self" id="s1">
<div>
       <marquee  scrollamount=50 width="90%">
     <img src="{% static 'img/s6.jpg' %}" class="img1">
     <img src="{% static 'img/1.png' %}"  class="img1">
     <img src="{% static 'img/3.jpg' %}" class="img1">
        </marquee>
     </div>
        </a>

 .img1
{
 margin-right:5px;
  border: 1px solid #ddd; /* Gray border */
  border-radius: 4px;  /* Rounded border */
  width:300px; /* Set a small width */
  height:200px;
}

Project/news aggregator/sample/templates/showusers.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>userdet</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<!--style>
    table {
  background-color: lightgrey;
  width: 400px;
  border: 15px solid black;
  padding: 50px;
  margin: 20px;
}
</style-->

<body>
<center>
    <div class="container" style="width:500px">
<table class="table table-bordered" >
<caption><h2> User detail </h2></caption>

        <tr align="left">
         <th> Id </th>
         <th> Name</th>
         <th> Password</th>
         <th> Actions </th>
        </tr>

{% for U in users %}
<tr>
    <td> {{ U.id}}</td>
    <td> {{ U.name}}</td>
    <td> {{ U.psw}}</td>
    <td> <a href="/edit/{{ U.id }}" class="btn btn-success">Edit</a>&nbsp;<a href="/delete/{{ U.id }}" class="btn btn-danger">Delete</a></td>
</tr>
{% endfor %}

</table>
    </center>
</div>
<br>
<br>
</body>
</html>

Project/news aggregator/sample/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
<link href="{% static 'css/s1.css' %}" rel="stylesheet" type="text/css" />
    <title>Title</title>
</head>
<body>
<div class="form">

      <ul class="tab-group">
        <li class="tab active"><a href="#signup">Sign Up</a></li>
        <li class="tab"><a href="#login">Log In</a></li>
      </ul>

      <div class="tab-content">
        <div id="signup">
          <h1>Sign Up for Free</h1>

          <form action="/" method="post">

          <div class="top-row">
            <div class="field-wrap">
              <label>
                First Name<span class="req">*</span>
              </label>
              <input type="text" required autocomplete="off" />
            </div>

            <div class="field-wrap">
              <label>
                Last Name<span class="req">*</span>
              </label>
              <input type="text"required autocomplete="off"/>
            </div>
          </div>

          <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input type="email"required autocomplete="off"/>
          </div>

          <div class="field-wrap">
            <label>
              Set A Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off"/>
          </div>

          <button type="submit" class="button button-block"/>Get Started</button>

          </form>

        </div>

        <div id="login">
          <h1>Welcome Back!</h1>

          <form action="/" method="post">

            <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input type="email"required autocomplete="off"/>
          </div>

          <div class="field-wrap">
            <label>
              Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off"/>
          </div>

          <p class="forgot"><a href="#">Forgot Password?</a></p>

          <button class="button button-block"/>Log In</button>

          </form>

        </div>

      </div><!-- tab-content -->

</div> <!-- /form -->
</form>
</body>
</html>

Project/news aggregator/sample/templates/userdet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>admin</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<style>
div {
  background-color: lightgrey;
  width: 400px;
  border: 15px solid green;
  padding: 50px;
  margin: 20px;
}
</style>

<body>

<form method="post" class="form" action="/insuser/">
    {% csrf_token %}
    <center>
        <div>
         <br>
            <h2> User Detail </h2>
             <br>
            <table>
               {{ form.as_table }}
          </table>
            <br>
          <button type= "submit" class="submit class=btn btn-success"> SUBMIT</button>
        </div>
    </center>
</form>
</body>
</html>